# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: treasurer 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "treasurer"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Edmund Highcock"]
  s.date = "2014-05-30"
  s.description = "A simple command line tool for managing accounts and finances. Easily import internet banking spreadsheets and generate sophisticated reports and projections."
  s.email = "edmundhighcock@users.sourceforge.net"
  s.executables = ["treasurer"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/treasurer",
    "lib/treasurer.rb",
    "lib/treasurer/analysis.rb",
    "lib/treasurer/commands.rb",
    "lib/treasurer/local_customisations.rb",
    "lib/treasurer/report.rb",
    "test/bankaccountstatement.csv",
    "test/helper.rb",
    "test/multiple/FirstBank.csv",
    "test/multiple/SecondBank.csv",
    "test/otheraccountstatement.csv",
    "test/test_treasurer.rb",
    "treasurer.gemspec"
  ]
  s.homepage = "http://github.com/edmundhighcock/treasurer"
  s.licenses = ["GPLv3"]
  s.rubygems_version = "2.2.2"
  s.summary = "A simple command line tool for managing accounts and finances."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<coderunner>, [">= 0.14.16"])
      s.add_runtime_dependency(%q<budgetcrmod>, [">= 0.0.0"])
      s.add_runtime_dependency(%q<command-line-flunky>, [">= 1.0.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<coderunner>, [">= 0.14.16"])
      s.add_dependency(%q<budgetcrmod>, [">= 0.0.0"])
      s.add_dependency(%q<command-line-flunky>, [">= 1.0.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<coderunner>, [">= 0.14.16"])
    s.add_dependency(%q<budgetcrmod>, [">= 0.0.0"])
    s.add_dependency(%q<command-line-flunky>, [">= 1.0.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

