# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: treasurer 0.10.0 ruby lib

Gem::Specification.new do |s|
  s.name = "treasurer".freeze
  s.version = "0.10.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Edmund Highcock".freeze]
  s.date = "2018-08-01"
  s.description = "A simple command line tool for managing accounts and finances. Easily import internet banking spreadsheets and generate sophisticated reports and projections.".freeze
  s.email = "edmundhighcock@users.sourceforge.net".freeze
  s.executables = ["treasurer".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/treasurer",
    "lib/treasurer.rb",
    "lib/treasurer/account_choices.rb",
    "lib/treasurer/accounts.rb",
    "lib/treasurer/analysis.rb",
    "lib/treasurer/commands.rb",
    "lib/treasurer/local_customisations.rb",
    "lib/treasurer/report.rb",
    "test/account_choices.rb",
    "test/bankaccountstatement.csv",
    "test/bankaccountstatementduplicate.csv",
    "test/external_accounts.rb",
    "test/helper.rb",
    "test/multiple/FirstBank.csv",
    "test/multiple/SecondBank.csv",
    "test/otheraccountstatement.csv",
    "test/test_treasurer.rb",
    "treasurer.gemspec"
  ]
  s.homepage = "http://github.com/edmundhighcock/treasurer".freeze
  s.licenses = ["GPLv3".freeze]
  s.rubygems_version = "2.6.8".freeze
  s.summary = "A simple command line tool for managing accounts and finances.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>.freeze, [">= 5.0.0"])
      s.add_runtime_dependency(%q<coderunner>.freeze, [">= 0.14.16"])
      s.add_runtime_dependency(%q<budgetcrmod>.freeze, ["~> 0.5.0"])
      s.add_runtime_dependency(%q<command-line-flunky>.freeze, [">= 1.0.0"])
      s.add_runtime_dependency(%q<sqlite3>.freeze, ["~> 1.3"])
      s.add_development_dependency(%q<shoulda>.freeze, [">= 0"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.3.1"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_development_dependency(%q<ruby-prof>.freeze, [">= 0.15"])
    else
      s.add_dependency(%q<activesupport>.freeze, [">= 5.0.0"])
      s.add_dependency(%q<coderunner>.freeze, [">= 0.14.16"])
      s.add_dependency(%q<budgetcrmod>.freeze, ["~> 0.5.0"])
      s.add_dependency(%q<command-line-flunky>.freeze, [">= 1.0.0"])
      s.add_dependency(%q<sqlite3>.freeze, ["~> 1.3"])
      s.add_dependency(%q<shoulda>.freeze, [">= 0"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.3.1"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_dependency(%q<ruby-prof>.freeze, [">= 0.15"])
    end
  else
    s.add_dependency(%q<activesupport>.freeze, [">= 5.0.0"])
    s.add_dependency(%q<coderunner>.freeze, [">= 0.14.16"])
    s.add_dependency(%q<budgetcrmod>.freeze, ["~> 0.5.0"])
    s.add_dependency(%q<command-line-flunky>.freeze, [">= 1.0.0"])
    s.add_dependency(%q<sqlite3>.freeze, ["~> 1.3"])
    s.add_dependency(%q<shoulda>.freeze, [">= 0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.3.1"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_dependency(%q<ruby-prof>.freeze, [">= 0.15"])
  end
end

